---
minimum_pre_commit_version: 1.15.2
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: check-merge-conflict  # Check for files that contain merge conflict strings.
      - id: trailing-whitespace   # Trims trailing whitespace.
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending     # Replaces or checks mixed line ending.
        args: [--fix=lf]
      - id: end-of-file-fixer     # Makes sure files end in a newline and only a newline.
      - id: check-merge-conflict  # Check for files that contain merge conflict strings.
      - id: check-ast             # Simply check whether files parse as valid python.
  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21
    hooks:
      - id: isort
        args:
          - -sp
          - setup.cfg
          - --recursive
          - -a
          - from __future__ import absolute_import, print_function, unicode_literals
          - --skip
          - versioneer.py
          - --skip
          - saltfactories/_version.py
        files: .*\.py$
  - repo: https://github.com/s0undt3ch/sq-black
    rev: v2019.1.15
    hooks:
      - id: sq-black
        args: [-l 100]
        exclude: (versioneer.py|saltfactories/_version.py)
        language_version: python3.6
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.3.1
    hooks:
      - id: pylint
        name: PyLint
        args: [--output-format=parseable, --rcfile=.pylintrc]
        exclude: (versioneer.py|saltfactories/_version.py)
        additional_dependencies:
          - saltpylint
